### server port
server.port=8081
spring.application.name=Spring Boot 2 with Keycloak 26

#Keycloak Configuration
keycloak.auth-server-url=http://localhost:8080/
keycloak.realm=spring-boot
keycloak.resource=spring-boot-client
keycloak.public-client=false
keycloak.bearer-only=false
keycloak.principal-attribute=preferred_username
keycloak.credentials.secret=L64Y6rfiEyN2H6QNySsKOuOifr8KATCe

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

keycloak.security-constraints[0].securityCollections[0].patterns[0]=/admin/*
keycloak.security-constraints[0].authRoles[0]=**